name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Verify Tailwind issue removed
        run: npm ls @tailwindcss/oxide || true

      - name: Build React app
        run: npm run build

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactapp .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/reactapp ${{ secrets.DOCKER_USERNAME }}/reactapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/reactapp:latest