name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (clean)
        run: npm ci --include=dev

      - name: Debug node_modules (check vite)
        run: ls -l node_modules/vite/bin

      - name: Build React app (FINAL FIX)
        run: node node_modules/vite/bin/vite.js build

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactapp .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/reactapp ${{ secrets.DOCKER_USERNAME }}/reactapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/reactapp:latest
